<h1 class="slanted">Designers</h1>

<?php
$designer_sets = array(
	"Ready-to-Wear" => array(
		array(
			"key"=>"aryn-k",
			"link"=>"aryn-k",
			"name"=>"Aryn K.",
			"description"=>"Aryn K., known for their ability to embody the lifestyle of the modern woman, always delivers when it comes to everyday ready-to-wear apparel.  The Aryn K. woman expresses her style and individuality through flowing blouses and tops for daytime and embellished dresses in the evenings.  A common thread throughout the Aryn K. line is versatility."
		),
		array(
			"key"=>"bcbgeneration",
			"link"=>"bcbgeneration",
			"name"=>"BCBGeneration",
			"description"=>"BCBGeneration created by Max Azria brings European fashion to America's doorstep.  \"Bon Chic, Bon Genre\" (BCBG)-- it's in the name.  BCBGeneration delivers good style and good attitude to women through delicate fabrics and trendy, unique cuts that take you from casual to evening effortlessly.  BCBG never underestimates the need for everyday comfort as well.  Preppy, bohemian, edgy, or put-together; there is something for everyone in this line.  Inspired by the spirit and sensibility of their customers, BCBG joins every-changing trends and classic styles to create a distinct look."
		),
		array(
			"key"=>"bcbg-max-azria",
			"link"=>"bcbg-max-azria",
			"name"=>"BCBG Max Azria",
			"description"=>"BCBG Max Azria is the premier lifestyle brand from designer and creator Max Azria (also of BCBGeneration).  \"Bon Chic, Bon Genre\" (BCBG) it's in the name.  Once again, Azria delivers the height of European designer fashion into the hands of the U.S. consumer on a dime.  BCBG Max Azria does not disappoint.  The line's timeless design and high-quality fabrics are innovative and lend themselves perfectly to effortless chic."
		),
		array(
			"key"=>"bella-luxx",
			"link"=>"bella-luxx",
			"name"=>"Bella Luxx",
			"description"=>"Bella Luxx, created by the partnership of two lifetime friends, is inspired by west coast lifestyle and simplicity.  Each silhouette screams with luxury and sleek design.  Not only the look of a perfect tee, but the feel of soft, lush fabrics will lure you into the Bella Luxx way of life.  Bella Luxx creates the perfect transitional tee with delicate cuts and ingenious draping proving that less really is more."
		),
		array(
			"key"=>"bobi",
			"link"=>"bobi",
			"name"=>"Bobi",
			"description"=>"With beginnings as a small family-operated business, Bobi creates unique luxury sportswear at competitive price points without compromising quality.  This simple yet sophisticated tee-shirt line is full of lush fabrics designed by LA based Kara Lusardi.  Simple and slim-fitting styles combine with unique fabrics to create comfortable and tasteful basics.  Bobi creates a lifestyle with casual soft lines and luxury texture to make women look and feel exquisite.  The fit, color, and design of these basics will leave you wanting more and more."
		),
		array(
			"key"=>"c-luce",
			"link"=>"c-luce",
			"name"=>"C. Luce",
			"description"=>"C. Luce is designed for sophistication.  Not only will you find truly unique patterns, shapes and textures; but also the ability to add color to your wardrobe effortlessly.  C. Luce prides themselves on the versatility and quality of their line.  Each piece has both the ability to be glamorous and functional simultaneously."
		),
		array(
			"key"=>"charlie-jade",
			"link"=>"charlie-jade",
			"name"=>"Charlie Jade",
			"description"=>"Charlie Jade is a one-of-a-kind brand.  The line is a unique mix of style, beauty and quality that always delivers a seamlessly modern silhouette.  Charlie Jade dresses, rompers, and blouses are the perfect mix of textured and colored silks full of playfulness, creativity, fantasy and surprise.  Each piece can go from day to night with simple accessories and a classic pump."
		),
		array(
			"key"=>"collective-concepts",
			"link"=>"collective-concepts",
			"name"=>"Collective Concepts",
			"description"=>"Collective Concepts is a young contemporary collection that is design-oriented and constantly evolving.  Based in LA, this stylish line is for the budget conscious consumer who believes in relevant design and premium workmanship.  Collective Concepts constantly delivers concise design and playful patterns for everyday wear."
		),
		array(
			"key"=>"ellison",
			"link"=>"ellison",
			"name"=>"Ellison",
			"description"=>"Ellison, established in 2006, is an upscale line that is not only feminine but innovative.   Ellison's delicate knits deliver moderate price without skimping on quality.  Their designs are sophisticated and on-point with the latest trends.  Try one of their comfortable knits on for size.  You will not be disappointed."
		),
		array(
			"key"=>"esley",
			"link"=>"esley",
			"name"=>"Esley",
			"description"=>"Established in 2007, Esley, named after its founder, exceeds the expectations of its followers.  Esley delivers classic edge and impeccable design in each piece.  This kind of affordability is not often matched with high-quality designer clothing.  Esley has an eye for fashion and modern sophistication.  This premier young contemporary line will not disappoint."
		),
		array(
			"key"=>"fluxus",
			"link"=>"fluxus",
			"name"=>"Fluxus",
			"description"=>"Fluxus creator Martin Paquette was influenced by Dadaism and futurist performance when he began his journey as founder of Fluxus, meaning \"to flow\" in Latin.  His designs break from tradition to give its customer the ability of self-expression through wardrobe.  Each piece in this line breathes in art.  The textures are simple and tactile; the cuts—avant-garde.  The relationship between everyday life and art is what Fluxus is all about."
		),
		array(
			"key"=>"french-connection",
			"link"=>"french-connection",
			"name"=>"French Connection",
			"description"=>"FCUK (French Connection UK) has built the most highly recognized brand in the UK, proving that their business really is fashion.  French Connection, founded in 1969 by Stephen Marks, features fashion-forward, contemporary designs.  On the leading edge of high-street fashion, French Connection has built its success on quality fashions that are stylish, hip, fashionable, and well-made."
		),
		array(
			"key"=>"glam",
			"link"=>"glam",
			"name"=>"Glam",
			"description"=>"Glam, a trendsetter in the contemporary market, appeals to fashionistas everywhere.  Founded in 1987, Glam's fashion-forward design of chic and wearable pieces allows for a perfect mix of feminine and flirty. Each element is beautiful, wearable, and attainable.  The Glam line incorporates an element of fun through print, color and silhouette.  Dazzling dresses, tops, bottoms, and outerwear all display the glamour and sophistication that is Glam."
		),
		array(
			"key"=>"greylin",
			"link"=>"greylin",
			"name"=>"Greylin",
			"description"=>"Greylin's eclectic style and beautiful craftsmanship meets the needs of the everyday woman to a \"t\".  The clean lines, alluring prints, and simple versatility breathes life into each piece.  Not only is each element chic and high-fashion, but also delivers an attention to detail and uniqueness for an affordable price.  Greylin serves up bold prints and embellishments with ease making it a stand-out among young contemporary lines."
		),
		array(
			"key"=>"jaloux",
			"link"=>"jaloux",
			"name"=>"Jaloux",
			"description"=>"Jaloux has been instilling confidence, femininity and sex appeal into their customers since 1998.  With the contemporary customer in mind, Jaloux pulls inspiration from European fashion.  Pieces from the Jaloux line feature detailed beading, metallics, lace, and a luxurious mix of fabrics.  Altogether, these elements form the perfect mixed media piece that is Jaloux.  With the ability to compliment denim or stand alone, these works of art are a wardrobe must-have."
		),
		array(
			"key"=>"la-made",
			"link"=>"la-made",
			"name"=>"LA Made",
			"description"=>"In the spirit of the SoCal lifestyle, LA Made, follows the fashions of today as they evolve into the trends of tomorrow.  The LA Made line is unique, understated and full of perfect basics, novelty pieces, and effortless style.  Always delivering classic feminine elements with a swift attention to detail and fit; LA Made is the ultimate contemporary fashion label.  The simple luxury of this line is unique, understated, and easy to wear.  LA Made takes cues from music, travel, real people and everyday life."
		),
		array(
			"key"=>"laila-jayde",
			"link"=>"laila-jayde",
			"name"=>"Laila Jayde",
			"description"=>"Laila Jayde is spuring change in US manufactured clothing.  The Laila Jayde line focuses on quality and fit.  Made from superior fabrics right here in the USA, these pieces have sensible, sexy and easy-to-wear designs that excite the senses.  Laila Jayde aims to make great fitting clothing and offer it to you at an accessible price point.  Designed and constructed for discerning tastes, Laila Jayde pieces are a great addition to any wardrobe."
		),
		array(
			"key"=>"laundry",
			"link"=>"laundry-by-shelli-segal",
			"name"=>"Laundry by Shelli Segal",
			"description"=>"Laundry by Shelli Segal, founded in 1988, is an LA based line that is constantly evolving with endless options to fit any lifestyle.  Laundry interprets the latest trends to create a go-to source for the contemporary woman balancing both work and play.  Inspired by an energetic and free-spirited attitude, Laundry by Shelli Segal creates a clean, feminine, and contemporary feel in each piece.  Laundry is a great source for the perfect dress for any occasion."
		),
		array(
			"key"=>"max-cleo",
			"link"=>"max-and-cleo",
			"name"=>"Max and Cleo",
			"description"=>"Inspired by multifaceted lifestyles, Max and Cleo offers the most stylish dresses that fit seamlessly into any wardrobe.  Max and Cleo, a division of BCBG Max Azria group, makes everyday wear fashionable with the versatility to take day to evening and work to weekend.  This line offers contemporary designs that are flattering on any figure.  From jersey bodies and faux wraps to sweet and sexy eveningwear, Max and Cleo has cornered the market on stylish staples at accessible prices."
		),
		array(
			"key"=>"michael-kors",
			"link"=>"michael-kors",
			"name"=>"Michael Kors",
			"description"=>"Michael Kors, a pre-eminent designer for luxury sportswear, established his line in 1981.  Both glamorous and sporty, this ready-to-wear line gives attention to both detail and quality.  Using the finest materials and fabrics, Michael Kors creates the ultimate chic look when it comes to luxury sportswear.  Buy a Michael Kors piece today and you will still be sporting it years from now."
		),
		array(
			"key"=>"minuet",
			"link"=>"minuet",
			"name"=>"Minuet",
			"description"=>"Minuet, a young contemporary line, is artfully crafted through vintage, runway, and couture inspiration.  Trendy, bold, feminine, and fun, Minuet has what you need to make an entrance at your next event.  This stand out brand is sophisticated and fabulous!"
		),
		array(
			"key"=>"theme",
			"link"=>"theme",
			"name"=>"Theme",
			"description"=>"Theme is a young contemporary line established in 2007 out of Los Angeles, California.  Theme bases seasonal collections on two concepts:  \"flirty-sophistication\" for Spring lines and \"edgy-chic\" for Fall lines.  Tops and dresses make up the greatest portion of the Theme line and carry the customer from day to evening effortlessly."
		),
		array(
			"key"=>"tricia-fix",
			"link"=>"tricia-fix",
			"name"=>"Tricia Fix",
			"description"=>"Tricia Fix, based in Florida, was founded in 2005.  The premise behind Tricia Fix's line is high-end red carpet meets affordability.  Tricia Fix pieces are comfortable, edgy, chic, and affordable.  She creates sexy silhouettes with flowing fabrics and unique embellishments."
		),
		array(
			"key"=>"tulle",
			"link"=>"tulle",
			"name"=>"Tulle",
			"description"=>"Tulle, founded in 1999, began with a focus on outerwear and sweaters and has developed into a full line that includes tops, skirts, and dresses.  Tulle's vintage-inspired modern silhouettes are feminine and sweet.  These pieces transition easily from day to night and satisfy a range of tastes from feminine and sweet to bohemian and hip.  Impeccable designs and cuts from Tulle make great staples in any closet."
		),
		array(
			"key"=>"vava",
			"link"=>"vava",
			"name"=>"VaVa",
			"description"=>"VaVa by Joy Han was launched in 2007 as a sister line to Voom by Joy Han.  Joy's vision was \"twisted vintage\" through fun prints and classic styles.  VaVa attempts to merge classic feminine cuts and edgy material mixes.  VaVa line offerings are also at accessible prices for the savvy shopper."
		),
		array(
			"key"=>"velvet-heart",
			"link"=>"velvet-heart",
			"name"=>"Velvet Heart",
			"description"=>"Velvet Heart is the perfect collection of novelty pieces and mixed media textures.  With new versions of classic fabrics and hand-detailed characteristics, this brand is perfect for the selective and not-so- ordinary consumer.  Specialty fabric treatments and fabrications merged with quality tailoring and perfect lines allow for Velvet Heart pieces to stand alone or pair with premium denim.  Feminine and vintage in its collection, Velvet Heart breathes life into high-end style and uptown edge."
		),
		array(
			"key"=>"voom",
			"link"=>"voom-by-joy-han",
			"name"=>"Voom by Joy Han",
			"description"=>"Launched in 2002 and mass produced in 2005, Voom by Joy Han began with just Joy and her husband.  Joy is the sole designer of her premier line, Voom, and created with it a new style genre she refers to as \"twisted-vintage\".  The Voom collection is full of novelty stand-alone pieces layered with quality fabrics and game-changing details."
		)
	),
	"Denim" => array(
		array(
			"key"=>"genetic-denim",
			"link"=>"genetic-denim",
			"name"=>"Genetic Denim",
			"description"=>"Founded by Ali Fatourechi in 2006, Genetic Denim delivers high-end premium denim that is cool and not fussy combined with the perfect fit.  Italian, Japanese, and Turkish denim in creative washes allows for a lean look and drape.  Genetic offers modern and classic shapes that sculpt a perfect silhouette yet allow for movement.  Fabrics are soft, luxurious, light and comfortable.  Styles in skinny, boot cut, bell-bottom, cigarette, and slim bell flare allow customers to fit individual curves with personal style."
		),
		array(
			"key"=>"hudson",
			"link"=>"hudson",
			"name"=>"Hudson",
			"description"=>"Hudson is \"instinct\".  Hudson premium denim is always perfectly tailored in British style with attitude and authenticity.  The quality of these denim pieces is uncompromising.  If the union jack logo and triangle pocket didn't give it away, this collection is English attitude meets LA attitude and Italian and Japanese denim.  Each piece is a jean to live in.  Both flattering and comfortable, Hudson jeans naturally complement each woman's distinct curves.  Hudson recreates your favorite jeans with spunk and cheeky style.  Perfect fit meets superior craftsmanship!"
		),
		array(
			"key"=>"paige",
			"link"=>"paige",
			"name"=>"Paige",
			"description"=>"Paige Premium Denim, created by former fit model Paige Adams-Geller, is one of the world's leading denim brands.  They have not only a signature \"perfect\" fit, but a variety of styles to fit the most discerning tastes.  Their innovative silhouettes and premium washes display ideal fit that is in line with the hottest trends.  Paige Premium Denim gives unmatched quality with the ability for self-expression in each piece."
		),
		array(
			"key"=>"true-religion",
			"link"=>"true-religion",
			"name"=>"True Religion",
			"description"=>"True Religion, founded in 2002 by Jeffrey Lubell, has redefined American made premium denim.  True Religion's mantra is \"hippie, bohemian, chic flair\" and it has solidified their brand position in the denim industry.  True Religion denim is authentic, timeless, and appeals to today's trendy consumer.  Each piece fits perfectly with 70's inspiration.  These jeans are a great addition to any wardrobe, and a staple for pairing with novelty blouses and boho-chic accessories."
		)
	),
	"Shoes" => array(
		array(
			"key"=>"bcbgeneration",
			"link"=>"bcbgeneration",
			"name"=>"BCBGeneration",
			"description"=>"BCBGeneration created by Max Azria brings European fashion to America's doorstep.  \"Bon Chic, Bon Genre\" (BCBG)-- it's in the name.  BCBGeneration delivers good style and good attitude to women through delicate fabrics and trendy, unique cuts that take you from casual to evening effortlessly.  BCBG never underestimates the need for everyday comfort as well.  Preppy, bohemian, edgy, or put-together; there is something for everyone in this line.  Inspired by the spirit and sensibility of their customers, BCBG joins every-changing trends and classic styles to create a distinct look."
		),
		array(
			"key"=>"plenty",
			"link"=>"plenty-by-tracy-reese",
			"name"=>"Plenty by Tracy Reese",
			"description"=>"Plenty by Tracy Reese is \"modern bohemian\".  Plenty's trend-relevant shoe line unites myth and modernity.  Each pair has a rock-and-roll twist created through detailing and embellishment.  The line's color palettes, lush fabrics, and adventurous spirit allow for timeless pieces you will be wearing again and again."
		),
		array(
			"key"=>"vince-camuto",
			"link"=>"vince-camuto",
			"name"=>"Vince Camuto",
			"description"=>"Vince Camuto worked his way to the top, beginning selling footwear and blazing a trail to provide stylish footwear for women at affordable prices.  Vince Camuto shoes are edgy, chic and fashion-forward not to mention high-quality.  With a modern, sexy edge, Vince's designs an styles showcase his passion for life, spirit and his work.  From flirty wedges to sexy heels, classic design to eye-catching embellishments; Vince Camuto has definitely made his mark on elegant and contemporary women's footwear that compliments the most fashionable wardrobe."
		)
	),
	"Bags" => array(
		array(
			"key"=>"melie-bianco",
			"link"=>"melie-bianco",
			"name"=>"Melie Bianco",
			"description"=>"Melie Bianco, founded in 2003 by Melissa and William, is a family-owned business that strives to bring runway-inspired bags to the budget conscious woman.  Melie Bianco designs are an affordable luxury and are in-line with season trends.  This LA based accessory company touts stylish design, top-notch construction and high-quality vegan materials at a fraction of the cost of designer bags.  Melissa believes that a great accessory can carry nearly any outfit, and proves it through her collections."
		)
	)
);

foreach($designer_sets as $set_name => $designers) {
	echo '<h2 class="slanted">'.$set_name.'</h2>'."\n";
	$row = 'odd';
	echo '<table border="0" cellpadding="0" cellspacing="0" width="100%">'."\n";
	foreach($designers as $designer) {
		echo '<tr class="'.$row.'">'."\n";
		echo '<td class="left-cell">'."\n";
		echo '<div class="wrapper">'."\n";
		echo '<div class="name"><a href="/designer-products?by='.$designer['link'].'">'.$designer['name'].'</a></div>'."\n";
		echo '<div class="description">'.$designer['description'].'</div>'."\n";
		echo '</div>'."\n";
		echo '</td>'."\n";
		echo '<td class="right-cell" valign="middle">'."\n";
		echo '<div class="wrapper '.$designer['key'].'">'.$designer['name'].'</div>'."\n";
		echo '</td>'."\n";
		echo '</tr>'."\n";
		$row = ($row == 'odd') ? 'even' : 'odd';
	}
	echo '</table>'."\n";
}
?>