<script type="text/javascript" language="javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->getSkinUrl('js/'); ?>jquery.bxSlider.min.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->getSkinUrl('js/'); ?>jquery.ui.widget.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->getSkinUrl('js/'); ?>jquery.smoothDivScroll-1.1-min.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->getSkinUrl('js/'); ?>jquery.easyModal.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->getSkinUrl('js/'); ?>jquery.subscribePopup.js"></script>
<script type="text/javascript">
$.noConflict();
jQuery(document).ready(function($) {
	// Header Image Rotation
	var featured_image = $('div.featured-image ul.slider').bxSlider({
		auto: true,
		autoControls: false,
		autoHover: true,
		controls: false,
		mode: 'horizontal',
		pause: 5000,
		speed: 500
	});
	$('div.featured-image div.image-wrapper').hover(
		function() {
			$('div.featured-image div.controls').fadeIn(250);
			//$('div.featured-image div.control-buffer').fadeIn(250);
		},
		function() {
			$('div.featured-image div.controls').fadeOut(250);
			//$('div.featured-image div.control-buffer').fadeOut(250);
		}
	);
	$('div.featured-image div.controls a.prev').hover(
		function() { featured_image.stopShow(); },
		function() { featured_image.startShow(); }
	);
	$('div.featured-image div.controls a.next').hover(
		function() { featured_image.stopShow(); },
		function() { featured_image.startShow(); }
	);
	$('div.featured-image div.controls a.prev').click(function() { featured_image.goToPreviousSlide(); });
	$('div.featured-image div.controls a.next').click(function() { featured_image.goToNextSlide(); });
	
	// Designer Logo Scroller
	$("div#makeMeScrollable").smoothDivScroll({
		autoScroll: 'onstart',
		autoScrollDirection: 'backandforth',
		autoScrollStep: 1,
		autoScrollInterval: 10,
		scrollStep: 5,
		scrollInterval: 10,
		visibleHotSpots: 'always'
	});
	$('div.scrollWrapper').hover(
		function() { $("div#makeMeScrollable").smoothDivScroll("stopAutoScroll"); },
		function() { $("div#makeMeScrollable").smoothDivScroll("startAutoScroll"); }
	);
	var scroller_restart = '';
	$('div.designers .button').hover(
		function() { clearTimeout(scroller_restart); },
		function() { scroller_restart = setTimeout(function() { $("div#makeMeScrollable").smoothDivScroll("startAutoScroll"); }, 3000); }
	);
});
</script>

<div class="featured-image">
	<div class="image-wrapper">
		<ul class="slider">
		<!--
		******************************************************
		HEY KATHRYN, I'M HERE TO HELP YOU ALONG.  I'M NOT REAL
		<li><a href="<?php echo $this->getUrl('bottoms/skirts/bcbgeneration-stripe-panel-skirt'); ?>"><img src="<?php echo $this->getSkinUrl('images/media/home-header-image/bcbgeneration-stripe-panel-skirt.jpg'); ?>" alt="" border="0" height="530" width="940" /></a></li>
		******************************************************
		-->
		<li><a href="<?php echo $this->getUrl('new-arrivals-1/be30767cy'); ?>"><img src="<?php echo $this->getSkinUrl('images/media/home-header-image/bevello-slide-1.jpg'); ?>" alt="" border="0" height="525" width="960" /></a></li>
		<li><a href="<?php echo $this->getUrl('shoes'); ?>"><img src="<?php echo $this->getSkinUrl('images/media/home-header-image/bevello-slide-2.jpg'); ?>" alt="" border="0" height="525" width="960" /></a></li>
		<li><a href="<?php echo $this->getUrl('accessories/scarves'); ?>"><img src="<?php echo $this->getSkinUrl('images/media/home-header-image/bevello-slide-3.jpg'); ?>" alt="" border="0" height="525" width="960" /></a></li>
		</ul>
		<div class="controls">
			<a class="prev"></a>
			<a class="next"></a>
		</div>
		<a class="mobilearrow mobileprev"></a>
		<a class="mobilearrow mobilenext"></a>
		<?php /*<div class="control-buffer"></div>*/ ?>
	</div>
</div><!-- .featured-image -->
<script type="text/javascript" language="javascript" src="<?php echo $this->getSkinUrl('js/'); ?>jquery-ui.animations.min.js"></script>
<script type="text/javascript">
	(function($){
		$(document).ready(function(){
			var $featuredImage = $('.featured-image'),
				$left = $featuredImage.find('.mobileprev'),
				$right = $featuredImage.find('.mobilenext');
			$left.position({
				my: 'left center',
				at: 'left center',
				of: $featuredImage
			});
			$right.position({
				my: 'right center',
				at: 'right center',
				of: $featuredImage
			});
			$left.click(function(){$featuredImage.find('.controls .prev').click()});
			$right.click(function(){$featuredImage.find('.controls .next').click()});
		});
	})(jQuery);
</script>

<div class="smalldivider"></div>

<div class="homeboxes row" id="twoboxes">
	<div id="facebookbox" class="hometwobox">
		<a href="http://www.facebook.com/bevelloboutique" target="_blank"><img src="<?php echo $this->getSkinUrl('images/facebook-large.png'); ?>" alt="facebook-large" width="51" height="51" class="facebookbutton" /></a>
		<a href="http://www.facebook.com/bevelloboutique" target="_blank"><img src="<?php echo $this->getSkinUrl('images/go-now.png'); ?>" alt="go-now" width="148" height="51" class="gonowbutton" /></a>
		<span class="homesmalltext">"Like" us on</span></br>
		<span class="homelargetext">Facebook</span>
	</div>
	<div id="emailsignupbox" class="hometwobox">
		<span class="homesmalltext">Be the first to know about bevello</span><span class="homesmalltextgotham"> sales, specials, &amp; events</span>
		<div class="emailsignupbox">
			<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
			<!--
			<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
				<div class="form-subscribe">
					<input type="text" name="email" id="newsletter" title="" class="input-text required-entry validate-email homeemail" style="border:none;" value="Email Address" onfocus="this.value==this.defaultValue?this.value='':null" />
					<input type="image" title="<?php echo $this->__('Submit') ?>" class="emailbutton" src="<?php echo $this->getSkinUrl('images/email-submit-arrow.png'); ?>" />
				</div>
			</form>
			<script type="text/javascript">
			//<![CDATA[
			    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
			    new Varien.searchForm('newsletter-validate-detail', 'newsletter', '<?php /*echo $this->helper('newsletter')->__('Enter your email address')*/ ?>');
			//]]>
			</script>
			-->
		</div>
	</div>
	<div style="clear:both;"></div>
</div>

<div class="smalldivider"></div>

<div class="homeboxes row" id="threeboxes">
	<div class="homethreebox firstfeaturebox">
		<a href="<?php echo $this->getUrl('shoes'); ?>"><img src="<?php echo $this->getSkinUrl('images/home-box-1.jpg'); ?>" alt="facebook-large" width="310" height="235" /></a>
	</div>
	<div class="homethreebox">
		<a href="<?php echo $this->getUrl('tops'); ?>"><img src="<?php echo $this->getSkinUrl('images/home-box-2.jpg'); ?>" alt="facebook-large" width="310" height="235" /></a>
	</div>
	<div class="homethreebox">
		<a href="<?php echo $this->getUrl('accessories'); ?>"><img src="<?php echo $this->getSkinUrl('images/home-box-3.jpg'); ?>" alt="facebook-large" width="310" height="235" /></a>
	</div>
	<div style="clear:both;"></div>
</div>

<div id="subscribe-dialog">
	<div class="subscribe-dialog-content">
		<h1>Join <span>the List</span></h1>
		<h2><span>Be the first to know</span> about private promotions,  new arrivals, bevello exclusives and more.</h2>
		<form action="/subscribe.php" method="post">
			<input type="hidden" name="id" value="Main" />
			<label for="mce-FNAME">
				First Name
				<input id="mce-FNAME" name="FNAME" type="text" />
			</label>
			<label for="mce-LNAME">
				Last Name
				<input id="mce-LNAME" name="LNAME" type="text" />
			</label>
			<label for="mce-EMAIL">
				Email
				<input id="mce-EMAIL" name="EMAIL" type="text" />
			</label>
			<label for="mce-CONFIRM">
				Confirm Email
				<input id="mce-CONFIRM" type="text" />
			</label>
			<div class="subscribe-dialog-control-group">
				<label for="mce-STATE">
					State
					<select id="mce-STATE" name="STATE">
						<option value="AL">AL</option>
						<option value="AK">AK</option>
						<option value="AZ">AZ</option>
						<option value="AR">AR</option>
						<option value="CA">CA</option>
						<option value="CO">CO</option>
						<option value="CT">CT</option>
						<option value="DE">DE</option>
						<option value="DC">DC</option>
						<option value="FL">FL</option>
						<option value="GA">GE</option>
						<option value="HI">HI</option>
						<option value="ID">ID</option>
						<option value="IL">IL</option>
						<option value="IN">IN</option>
						<option value="IA">IA</option>
						<option value="KS">KS</option>
						<option value="KY">KY</option>
						<option value="LA">LA</option>
						<option value="ME">ME</option>
						<option value="MD">MD</option>
						<option value="MA">MA</option>
						<option value="MI">MI</option>
						<option value="MN">MN</option>
						<option value="MS">MS</option>
						<option value="MO">MO</option>
						<option value="MT">MT</option>
						<option value="NE">NE</option>
						<option value="NV">NV</option>
						<option value="NH">NH</option>
						<option value="NJ">NJ</option>
						<option value="NM">NM</option>
						<option value="NY">NY</option>
						<option value="NC">NC</option>
						<option value="ND">ND</option>
						<option value="OH">OH</option>
						<option value="OK">OK</option>
						<option value="OR">OR</option>
						<option value="PA">PA</option>
						<option value="RI">RI</option>
						<option value="SC">SC</option>
						<option value="SD">SD</option>
						<option value="TN">TN</option>
						<option value="TX">TX</option>
						<option value="UT">UT</option>
						<option value="VT">VT</option>
						<option value="VA">VA</option>
						<option value="WA">WA</option>
						<option value="WV">WV</option>
						<option value="WI">WI</option>
						<option value="WY">WY</option>
					</select>
				</label>
				<label for="mce-POSTAL">
					ZIP Code
					<input id="mce-POSTAL" name="POSTAL" type="text" />
				</label>
			</div>
			<label for="mce-BIRTHMONTH">Birthday <em>(We like to give surprises!)</em>
				<select id="mce-BIRTHMONTH">
					<option value="01">January</option>
					<option value="02">February</option>
					<option value="03">March</option>
					<option value="04">April</option>
					<option value="05">May</option>
					<option value="06">June</option>
					<option value="07">July</option>
					<option value="08">August</option>
					<option value="09">September</option>
					<option value="10">October</option>
					<option value="11">November</option>
					<option value="12">December</option>
				</select>
				<input id="mce-BIRTHDAY" type="number" min="1" max="31" />
				<input type="hidden" name="BIRTHDAY" value="" id="mce-REAL-BIRTHDAY" />
			</label>
			<input id="mce-SUBMIT" value="Submit ▸" type="submit" />
		</form>
	</div>
</div>

<script type="text/javascript">
	(function($){
		$('#subscribe-dialog').appendTo($('body').first()).subscribePopup({id: 'Main'});
	})(jQuery);
</script>

