<div class="smalldivider"></div>

<div class="homeboxes row" id="twoboxes">
	<div id="facebookbox" class="hometwobox">
		<a href="http://www.facebook.com/bevelloboutique" target="_blank"><img src="<?php echo $this->getSkinUrl('images/facebook-large.png'); ?>" alt="facebook-large" width="51" height="51" class="facebookbutton" /></a>
		<a href="http://www.facebook.com/bevelloboutique" target="_blank"><img src="<?php echo $this->getSkinUrl('images/go-now.png'); ?>" alt="go-now" width="148" height="51" class="gonowbutton" /></a>
		<span class="homesmalltext">"Like" us on</span></br>
		<span class="homelargetext">Facebook</span>
	</div>
	<div id="emailsignupbox" class="hometwobox">

		<span class="homesmalltext">Be the first to know about bevello</span><span class="homesmalltextgotham"> offers, events & more</span>

		<div class="emailsignupbox">
			<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?>
		</div>
	</div>
	<div style="clear:both;"></div>
</div>

<div class="smalldivider"></div>



